scenario_env_json: data/ds_1.json
output_path: outputs/ds_1_v2 # absolute path
lgsvl_map: SanFrancisco_correct
apollo_map: SanFrancisco

pop_size: 4
npc_size: 2
time_size: 30
conflict_time: 4
conflict_distance: 3
period: 6
bounds: [[5, 30], [0, 3], [0,2], [0,2], [2,4]]
total_sim_time: 30
p_mutation: 0.4
p_crossover: 0.4
max_gen: 100
selection: roulette

# apollo reltaed path config
default_record_folder: /home/tieriv/alsachai/apollo/data/bag # False means ignoring records